import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";

import { Play } from "next/font/google";
import Hero from "@/Containers/Hero";
import About from "@/Containers/About";
import Statistics from "@/Containers/Statistics"
import FAQ from "@/Containers/FAQ";


const play = Play({ weight: "700", subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <Hero id="#home"></Hero>
      <About id="#about"></About>
      <Statistics id="#statistics"></Statistics>
      <FAQ id="#faq"></FAQ>
      </main>
    </>
  );
}